In [10]:
import tensorflow as tf
import numpy as np
print(tf.__version__)
# 张量
print(tf.add(1,2))
print(tf.add([1,2],[3,4]))
print(tf.square(6))
print(tf.reduce_sum([7,8,9]))

2.0.0
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(36, shape=(), dtype=int32)
tf.Tensor(24, shape=(), dtype=int32)


In [11]:
x = tf.matmul([[3],[6]],[[2]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(
[[ 6]
 [12]], shape=(2, 1), dtype=int32)
(2, 1)
<dtype: 'int32'>


In [12]:
n = np.ones([2,2])
tensor = tf.multiply(n,32)
print(tensor)
# tensor转numpy
print(tensor.numpy())

tf.Tensor(
[[32. 32.]
 [32. 32.]], shape=(2, 2), dtype=float64)
[[32. 32.]
 [32. 32.]]


In [13]:
# GPU &CPU test
print(tf.test.is_gpu_available())

False


In [15]:
# 数据集
data = tf.data.Dataset.from_tensor_slices([6,5,4,3,2,1])
# csv数据
import tempfile
_,filename = tempfile.mkstemp()
print(filename)
with open(filename,'w') as f:
    f.write("""
    Line 1
    Line 2
    Line 3
    """)
data = tf.data.TextLineDataset(filename)

/tmp/tmpbis2mt4g
